
pm disable-user --user 0 android.auto_generated_rro_product__
pm disable-user --user 0 android.auto_generated_rro_vendor__
pm disable-user --user 0 android.autoinstalls.config.samsung
pm disable-user --user 0 android.apps.tag
pm disable-user --user 0 android.backupconfirm
pm disable-user --user 0 android.bips
pm disable-user --user 0 android.bluetoothmidiservice
pm disable-user --user 0 android.bookmarkprovider
pm disable-user --user 0 android.calllogbackup
pm disable-user --user 0 android.carrierdefaultapp
pm disable-user --user 0 android.certinstaller
pm disable-user --user 0 android.companiondevicemanager
pm disable-user --user 0 android.cts.ctsshim
pm disable-user --user 0 android.cts.priv.ctsshim
pm disable-user --user 0 android.dreams.basic
pm disable-user --user 0 android.dreams.phototable
pm disable-user --user 0 android.dynsystem
pm disable-user --user 0 android.egg
pm disable-user --user 0 android.emergency
pm disable-user --user 0 android.hotspot2.osulogin
pm disable-user --user 0 android.internal.display.cutout.emulation.corner
pm disable-user --user 0 android.internal.display.cutout.emulation.double
pm disable-user --user 0 android.internal.display.cutout.emulation.hole
pm disable-user --user 0 android.internal.display.cutout.emulation.tall
pm disable-user --user 0 android.internal.display.cutout.emulation.waterfall
pm disable-user --user 0 android.internal.systemui.navbar.gestural
pm disable-user --user 0 android.internal.systemui.navbar.gestural_extra_wide_back
pm disable-user --user 0 android.internal.systemui.navbar.gestural_narrow_back
pm disable-user --user 0 android.internal.systemui.navbar.gestural_wide_back
pm disable-user --user 0 android.internal.systemui.navbar.threebutton
pm disable-user --user 0 android.keychain
pm disable-user --user 0 android.localtransport
pm disable-user --user 0 android.managedprovisioning
pm disable-user --user 0 android.mms.service
pm disable-user --user 0 android.nfc
pm disable-user --user 0 android.ons
pm disable-user --user 0 android.pacprocessor
pm disable-user --user 0 android.printspooler
pm disable-user --user 0 android.providers.partnerbookmarks
pm disable-user --user 0 android.providers.userdictionary
pm disable-user --user 0 android.proxyhandler
pm disable-user --user 0 android.se
pm disable-user --user 0 android.settings.intelligence
pm disable-user --user 0 android.sharedstoragebackup
pm disable-user --user 0 android.simappdialog
pm disable-user --user 0 android.statementservice
pm disable-user --user 0 android.stk
pm disable-user --user 0 android.stk2
pm disable-user --user 0 android.storagemanager
pm disable-user --user 0 android.theme.color.black
pm disable-user --user 0 android.theme.color.cinnamon
pm disable-user --user 0 android.theme.color.green
pm disable-user --user 0 android.theme.color.ocean
pm disable-user --user 0 android.theme.color.orchid
pm disable-user --user 0 android.theme.color.purple
pm disable-user --user 0 android.theme.color.space
pm disable-user --user 0 android.theme.font.notoserifsource
pm disable-user --user 0 android.theme.icon.pebble
pm disable-user --user 0 android.theme.icon.roundedrect
pm disable-user --user 0 android.theme.icon.squircle
pm disable-user --user 0 android.theme.icon.taperedrect
pm disable-user --user 0 android.theme.icon.teardrop
pm disable-user --user 0 android.theme.icon.vessel
pm disable-user --user 0 android.theme.icon_pack.circular.android
pm disable-user --user 0 android.theme.icon_pack.circular.launcher
pm disable-user --user 0 android.theme.icon_pack.circular.settings
pm disable-user --user 0 android.theme.icon_pack.circular.systemui
pm disable-user --user 0 android.theme.icon_pack.circular.themepicker
pm disable-user --user 0 android.theme.icon_pack.filled.android
pm disable-user --user 0 android.theme.icon_pack.filled.launcher
pm disable-user --user 0 android.theme.icon_pack.filled.settings
pm disable-user --user 0 android.theme.icon_pack.filled.systemui
pm disable-user --user 0 android.theme.icon_pack.filled.themepicker
pm disable-user --user 0 android.theme.icon_pack.rounded.android
pm disable-user --user 0 android.theme.icon_pack.rounded.launcher
pm disable-user --user 0 android.theme.icon_pack.rounded.settings
pm disable-user --user 0 android.theme.icon_pack.rounded.systemui
pm disable-user --user 0 android.theme.icon_pack.rounded.themepicker
pm disable-user --user 0 android.traceur
pm disable-user --user 0 android.wallpaper.livepicker
pm disable-user --user 0 android.wallpaperbackup
pm disable-user --user 0 android.wallpapercropper
pm disable-user --user 0 aura.oobe.samsung.gl
pm disable-user --user 0 debug.loggerui
pm disable-user --user 0 diotek.sec.lookup.dictionary
pm disable-user --user 0 facebook.appmanager
pm disable-user --user 0 facebook.services
pm disable-user --user 0 facebook.system
pm disable-user --user 0 google.android.apps.carrier.carrierwifi
pm disable-user --user 0 google.android.apps.restore
pm disable-user --user 0 google.android.apps.tachyon
pm disable-user --user 0 google.android.apps.turbo
pm disable-user --user 0 google.android.as
pm disable-user --user 0 google.android.cellbroadcastreceiver
pm disable-user --user 0 google.android.cellbroadcastservice
pm disable-user --user 0 google.android.configupdater
pm disable-user --user 0 google.android.ext.services
pm disable-user --user 0 google.android.ext.shared
pm disable-user --user 0 google.android.feedback
pm disable-user --user 0 google.android.gms.location.history
pm disable-user --user 0 google.android.googlequicksearchbox
pm disable-user --user 0 google.android.networkstack.permissionconfig
pm disable-user --user 0 google.android.onetimeinitializer
pm disable-user --user 0 google.android.overlay.gmsconfig.common
pm disable-user --user 0 google.android.overlay.gmsconfig.gsa
pm disable-user --user 0 google.android.overlay.gmsconfig.photos
pm disable-user --user 0 google.android.overlay.modules.cellbroadcastreceiver
pm disable-user --user 0 google.android.overlay.modules.cellbroadcastservice
pm disable-user --user 0 google.android.overlay.modules.ext.services
pm disable-user --user 0 google.android.overlay.modules.modulemetadata.forframework
pm disable-user --user 0 google.android.partnersetup
pm disable-user --user 0 google.android.printservice.recommendation
pm disable-user --user 0 google.android.projection.gearhead
pm disable-user --user 0 google.android.setupwizard
pm disable-user --user 0 google.android.syncadapters.calendar
pm disable-user --user 0 google.android.syncadapters.contacts
pm disable-user --user 0 google.android.tts
pm disable-user --user 0 google.ar.core
pm disable-user --user 0 google.mainline.telemetry
pm disable-user --user 0 hiya.star
pm disable-user --user 0 knox.vpn.proxyhandler
pm disable-user --user 0 mediatek
pm disable-user --user 0 mediatek.systemuiresoverlay
pm disable-user --user 0 microsoft.appmanager
pm disable-user --user 0 microsoft.skydrive
pm disable-user --user 0 monotype.android.font.foundation
pm disable-user --user 0 monotype.android.font.samsungone
pm disable-user --user 0 netflix.mediaclient
pm disable-user --user 0 netflix.partner.activation
pm disable-user --user 0 osp.app.signin
pm disable-user --user 0 samsung.aasaservice
pm disable-user --user 0 samsung.adaptivebrightnessgo
pm disable-user --user 0 samsung.advp.imssettings
pm disable-user --user 0 samsung.android.accessibility.talkback
pm disable-user --user 0 samsung.android.aircommandmanager
pm disable-user --user 0 samsung.android.allshare.service.fileshare
pm disable-user --user 0 samsung.android.allshare.service.mediashare
pm disable-user --user 0 samsung.android.app.appsedge
pm disable-user --user 0 samsung.android.app.clipboardedge
pm disable-user --user 0 samsung.android.app.cocktailbarservice
pm disable-user --user 0 samsung.android.app.galaxyfinder
pm disable-user --user 0 samsung.android.app.omcagent
pm disable-user --user 0 samsung.android.app.reminder
pm disable-user --user 0 samsung.android.app.settings.bixby
pm disable-user --user 0 samsung.android.app.sharelive
pm disable-user --user 0 samsung.android.app.simplesharing
pm disable-user --user 0 samsung.android.app.smartcapture
pm disable-user --user 0 samsung.android.app.spage
pm disable-user --user 0 samsung.android.app.taskedge
pm disable-user --user 0 samsung.android.app.watchmanagerstub
pm disable-user --user 0 samsung.android.appseparation
pm disable-user --user 0 samsung.android.ardrawing
pm disable-user --user 0 samsung.android.aremoji
pm disable-user --user 0 samsung.android.aremojieditor
pm disable-user --user 0 samsung.android.arzone
pm disable-user --user 0 samsung.android.authfw
pm disable-user --user 0 samsung.android.aware.service
pm disable-user --user 0 samsung.android.bbc.bbcagent
pm disable-user --user 0 samsung.android.beaconmanager
pm disable-user --user 0 samsung.android.bixbyvision.framework
pm disable-user --user 0 samsung.android.bluelightfilter
pm disable-user --user 0 samsung.android.brightnessbackupservice
pm disable-user --user 0 samsung.android.callbgprovider
pm disable-user --user 0 samsung.android.cidmanager
pm disable-user --user 0 samsung.android.cmfa.framework
pm disable-user --user 0 samsung.android.container
pm disable-user --user 0 samsung.android.da.daagent
pm disable-user --user 0 samsung.android.dqagent
pm disable-user --user 0 samsung.android.dsms
pm disable-user --user 0 samsung.android.dynamiclock
pm disable-user --user 0 samsung.android.easysetup
pm disable-user --user 0 samsung.android.fmm
pm disable-user --user 0 samsung.android.forest
pm disable-user --user 0 samsung.android.game.gamehome
pm disable-user --user 0 samsung.android.hdmapp
pm disable-user --user 0 samsung.android.icecone
pm disable-user --user 0 samsung.android.kidsinstaller
pm disable-user --user 0 samsung.android.knox.analytics.uploader
pm disable-user --user 0 samsung.android.knox.attestation
pm disable-user --user 0 samsung.android.knox.containeragent
pm disable-user --user 0 samsung.android.knox.containercore
pm disable-user --user 0 samsung.android.knox.pushmanager
pm disable-user --user 0 samsung.android.livestickers
pm disable-user --user 0 samsung.android.localeoverlaymanager
pm disable-user --user 0 samsung.android.location
pm disable-user --user 0 samsung.android.lool
pm disable-user --user 0 samsung.android.mapsagent
pm disable-user --user 0 samsung.android.mateagent
pm disable-user --user 0 samsung.android.mcfds
pm disable-user --user 0 samsung.android.mcfserver
pm disable-user --user 0 samsung.android.mdecservice
pm disable-user --user 0 samsung.android.mdm
pm disable-user --user 0 samsung.android.mdx
pm disable-user --user 0 samsung.android.mdx.kit
pm disable-user --user 0 samsung.android.mdx.quickboard
pm disable-user --user 0 samsung.android.mobileservice
pm disable-user --user 0 samsung.android.net.wifi.wifiguider
pm disable-user --user 0 samsung.android.networkdiagnostic
pm disable-user --user 0 samsung.android.networkstack
pm disable-user --user 0 samsung.android.networkstack.tethering.overlay
pm disable-user --user 0 samsung.android.privateshare
pm disable-user --user 0 samsung.android.providers.carrier
pm disable-user --user 0 samsung.android.rubin.app
pm disable-user --user 0 samsung.android.samsungpass
pm disable-user --user 0 samsung.android.samsungpassautofill
pm disable-user --user 0 samsung.android.scloud
pm disable-user --user 0 samsung.android.scs
pm disable-user --user 0 samsung.android.sdk.handwriting
pm disable-user --user 0 samsung.android.sdm.config
pm disable-user --user 0 samsung.android.securitylogagent
pm disable-user --user 0 samsung.android.server.wifi.mobilewips
pm disable-user --user 0 samsung.android.service.peoplestripe
pm disable-user --user 0 samsung.android.service.stplatform
pm disable-user --user 0 samsung.android.setting.multisound
pm disable-user --user 0 samsung.android.SettingsReceiver
pm disable-user --user 0 samsung.android.shortcutbackupservice
pm disable-user --user 0 samsung.android.sm.devicesecurity
pm disable-user --user 0 samsung.android.sm.policy
pm disable-user --user 0 samsung.android.smartcallprovider
pm disable-user --user 0 samsung.android.smartface
pm disable-user --user 0 samsung.android.smartmirroring
pm disable-user --user 0 samsung.android.smartsuggestions
pm disable-user --user 0 samsung.android.smartswitchassistant
pm disable-user --user 0 samsung.android.spayfw
pm disable-user --user 0 samsung.android.stickercenter
pm disable-user --user 0 samsung.android.svcagent
pm disable-user --user 0 samsung.android.tadownloader
pm disable-user --user 0 samsung.android.tapack.authfw
pm disable-user --user 0 samsung.android.themestore
pm disable-user --user 0 samsung.android.uds
pm disable-user --user 0 samsung.android.visionintelligence
pm disable-user --user 0 samsung.android.wallpaper.res
pm disable-user --user 0 samsung.android.wifi.resources
pm disable-user --user 0 samsung.android.wifi.softap.resources
pm disable-user --user 0 samsung.cmh
pm disable-user --user 0 samsung.crane
pm disable-user --user 0 samsung.faceservice
pm disable-user --user 0 samsung.ims.smk
pm disable-user --user 0 samsung.internal.systemui.navbar.gestural_no_hint
pm disable-user --user 0 samsung.internal.systemui.navbar.gestural_no_hint_extra_wide_back
pm disable-user --user 0 samsung.internal.systemui.navbar.gestural_no_hint_narrow_back
pm disable-user --user 0 samsung.internal.systemui.navbar.gestural_no_hint_wide_back
pm disable-user --user 0 samsung.internal.systemui.navbar.sec_gestural
pm disable-user --user 0 samsung.internal.systemui.navbar.sec_gestural_no_hint
pm disable-user --user 0 samsung.ipservice
pm disable-user --user 0 samsung.klmsagent
pm disable-user --user 0 samsung.knox.keychain
pm disable-user --user 0 samsung.knox.securefolder
pm disable-user --user 0 samsung.memorysaver
pm disable-user --user 0 samsung.rcs
pm disable-user --user 0 samsung.safetyinformation
pm disable-user --user 0 samsung.sec.android.application.csc
pm disable-user --user 0 samsung.SMT
pm disable-user --user 0 samsung.storyservice
pm disable-user --user 0 sec.android.app.billing
pm disable-user --user 0 sec.android.app.bluetoothtest
pm disable-user --user 0 sec.android.app.chromecustomizations
pm disable-user --user 0 sec.android.app.DataCreate
pm disable-user --user 0 sec.android.app.factorykeystring
pm disable-user --user 0 sec.android.app.fm
pm disable-user --user 0 sec.android.app.hwmoduletest
pm disable-user --user 0 sec.android.app.magnifier
pm disable-user --user 0 sec.android.app.parser
pm disable-user --user 0 sec.android.app.personalization
pm disable-user --user 0 sec.android.app.quicktool
pm disable-user --user 0 sec.android.app.ringtoneBR
pm disable-user --user 0 sec.android.app.safetyassurance
pm disable-user --user 0 sec.android.app.samsungapps
pm disable-user --user 0 sec.android.app.SecSetupWizard
pm disable-user --user 0 sec.android.app.servicemodeapp
pm disable-user --user 0 sec.android.app.setupwizardlegalprovider
pm disable-user --user 0 sec.android.app.soundalive
pm disable-user --user 0 sec.android.app.ve.vebgm
pm disable-user --user 0 sec.android.app.wlantest
pm disable-user --user 0 sec.android.autodoodle.service
pm disable-user --user 0 sec.android.daemonapp
pm disable-user --user 0 sec.android.diagmonagent
pm disable-user --user 0 sec.android.easyMover.Agent
pm disable-user --user 0 sec.android.emergencylauncher
pm disable-user --user 0 sec.android.emergencymode.service
pm disable-user --user 0 sec.android.mimage.avatarstickers
pm disable-user --user 0 sec.android.preloadinstaller
pm disable-user --user 0 sec.android.provider.badge
pm disable-user --user 0 sec.android.provider.emergencymode
pm disable-user --user 0 sec.android.RilServiceModeApp
pm disable-user --user 0 sec.android.sdhms
pm disable-user --user 0 sec.android.soagent
pm disable-user --user 0 sec.android.widgetapp.easymodecontactswidget
pm disable-user --user 0 sec.android.widgetapp.webmanual
pm disable-user --user 0 sec.app.RilErrorNotifier
pm disable-user --user 0 sec.automation
pm disable-user --user 0 sec.bcservice
pm disable-user --user 0 sec.enterprise.knox.attestation
pm disable-user --user 0 sec.enterprise.knox.cloudmdm.smdms
pm disable-user --user 0 sec.enterprise.mdm.services.simpin
pm disable-user --user 0 sec.epdg
pm disable-user --user 0 sec.epdgtestapp
pm disable-user --user 0 sec.factory
pm disable-user --user 0 sec.factory.camera
pm disable-user --user 0 sec.factory.cameralyzer
pm disable-user --user 0 sec.hearingadjust
pm disable-user --user 0 sec.imslogger
pm disable-user --user 0 sec.imsservice
pm disable-user --user 0 sec.location.nfwlocationprivacy
pm disable-user --user 0 sec.location.nsflp2
pm disable-user --user 0 sec.mhs.smarttethering
pm disable-user --user 0 sec.phone
pm disable-user --user 0 sec.spp.push
pm disable-user --user 0 sec.sve
pm disable-user --user 0 sec.unifiedwfc
pm disable-user --user 0 sec.vsim.ericssonnsds.webapp
pm disable-user --user 0 skms.android.agent
pm disable-user --user 0 trustonic.teeservice
pm disable-user --user 0 wsomacp
pm disable-user --user 0 wssyncmldm
